---
# tasks file for tomcat
- name: Download tomcat package
  command: "wget http://mirror.reverse.net/pub/apache/tomcat/tomcat-8/v8.5.59/bin/apache-tomcat-8.5.59.tar.gz"
  args:
     chdir: /tmp/

- name: Install java package
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - java-1.8.0-openjdk

- name: Extract Tomcat archive
  command: tar zxvf /tmp/apache-tomcat-8.5.59.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.59
  args:
     chdir: /tmp/
- name: Ansible template with_items example.
  template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0777
        backup: yes
        owner: root
        group: root
  with_items:
        - {src: '/etc/ansible/tomcat/templates/context.xml',dest: '/opt/apache-tomcat-8.5.59/webapps/manager/META-INF/'}
        - {src: '/etc/ansible/tomcat/templates/tomcat-users.xml',dest: '/opt/apache-tomcat-8.5.59/conf/'}


- name: copy arti facts to document root
  copy:
     src: /etc/ansible/sample.war
     dest: /opt/apache-tomcat-8.5.59/webapps/sample.war

#- name: Stop Tomcat
#  command: nohup /opt/apache-tomcat-8.5.59/bin/shutdown.sh

- name: Start Tomcat
  command: nohup /opt/apache-tomcat-8.5.59/bin/startup.sh
